apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-jira
  description: An example of a Backstage application.
  metadata:
    annotations:
      jira/project-key: KAN123
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
